name: sqflite_migrations_with_multiverse_time_travel
description: Runs database migrations for apps using sqflite. Check out different branches during development without having to reset the db.
version: 0.1.1
repository: https://github.com/benthillerkus/db_migrations_with_multiverse_time_travel
issue_tracker: https://github.com/benthillerkus/db_migrations_with_multiverse_time_travel/issues
topics: ["database", "migration", "sqflite"]
environment:
  sdk: ^3.5.0
screenshots:
  - description: The logo featuring two arrows representing version control branches flying into a clock
    path: logo.webp

resolution: workspace

# Add regular dependencies here.
dependencies:
  db_migrations_with_multiverse_time_travel: ^1.1.0
  meta: ^1.17.0
  sqflite_common: ^2.4.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  sqflite_common_ffi: ^2.2.1
  mutex: ^3.1.0
