name: workspace
version: 1.0.0
publish_to: none
repository: https://github.com/benthillerkus/db_migrations_with_multiverse_time_travel
issue_tracker: https://github.com/benthillerkus/db_migrations_with_multiverse_time_travel/issues
environment:
  sdk: ^3.5.0
workspace:
  - packages/generic
  - packages/sqlite3
  - packages/sqflite
  - packages/cbl