name: db_migrations_with_multiverse_time_travel
description: Runs database migrations for apps with local / embedded databases like SQLite. Helps with checking out different branches during development by storing the instructions to run down migrations alongside the data in the db.
version: 1.0.0
repository: https://github.com/benthillerkus/db_migrations_with_multiverse_time_travel
issue_tracker: https://github.com/benthillerkus/db_migrations_with_multiverse_time_travel/issues
topics: ["database", "migration"]
environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dependencies:
  logging: ^1.3.0
  meta: ^1.16.0

dev_dependencies:
  ansicolor: ^2.0.3
  collection:
  lints: ^5.0.0
  test: ^1.24.0
