name: db_migrations_with_multiverse_timetravel
description: Runs database migrations for apps with local / embedded databases like SQLite. Helps with checking out different branches during development by storing the instructions to run down migrations alongside the data in the db.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.7.0-323.0.dev'

resolution: workspace

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
