name: sqlite3_migrations_with_multiverse_time_travel
description: Runs database migrations for apps using sqlite3. Helps with checking out different branches during development by storing the instructions to run down migrations alongside the data in the db.
version: 1.0.0
repository: https://github.com/benthillerkus/db_migrations_with_multiverse_time_travel
issue_tracker: https://github.com/benthillerkus/db_migrations_with_multiverse_time_travel/issues
topics: ["database", "migration", "sqlite"]
environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

# Add regular dependencies here.
dependencies:
  db_migrations_with_multiverse_time_travel: ^1.0.0
  sqlite3: '>=2.0.0 <3.0.0'

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  path: ^1.9.1
  sqlite3_test: ^0.1.1
  file: ^7.0.1
  logging: ^1.3.0
  collection: ^1.19.1
