name: sqlite3_migrations_with_multiverse_time_travel
description: Runs database migrations for apps using sqlite3. Check out different branches during development without having to reset the db.
version: 1.0.2
repository: https://github.com/benthillerkus/db_migrations_with_multiverse_time_travel
issue_tracker: https://github.com/benthillerkus/db_migrations_with_multiverse_time_travel/issues
topics: ["database", "migration", "sqlite"]
environment:
  sdk: ^3.5.4
screenshots:
  - description: The logo featuring two arrows representing version control branches flying into a clock
    path: logo.webp

resolution: workspace

# Add regular dependencies here.
dependencies:
  db_migrations_with_multiverse_time_travel: ^1.0.1
  meta: ^1.3.0
  sqlite3: ^2.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.22.0
  path: ^1.8.0
  sqlite3_test: ^0.1.1
  file: '>=6.0.0 <8.0.0'
  logging: ^1.0.0
  collection: ^1.17.2
  fake_async: ^1.2.0
