name: Copy README

on:
  push:
    paths:
      - 'README.md'
    branches:
      - main

jobs:
  copy-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy README.md to packages/generic/README.md
        run: |
          cp README.md packages/generic/README.md
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4