name: Sync README

on:
  push:
    paths:
      - 'README.md'
    branches:
      - main

jobs:
  copy-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Copy README.md to packages/generic/README.md
        run: |
          cp README.md packages/generic/README.md
      
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add packages/generic/README.md
          git commit -m "docs(README.md) sync to packages/generic/README.md"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
