name: Sync README

on:
  push:
    paths:
      - 'README.md'
      - 'banner.webp'
      - 'logo.webp'
    branches:
      - main

jobs:
  copy-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - run: |
          cp README.md packages/generic/README.md
          for dir in $(dart pub workspace list --json | jq -r '.packages[] | select(.name != "workspace") | .path' | sed 's|${{ github.workspace }}/||g'); do
            cp banner.webp $dir/banner.webp
            cp logo.webp $dir/logo.webp
          done
      
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add packages/generic/README.md
          for dir in $(dart pub workspace list --json | jq -r '.packages[] | select(.name != "workspace") | .path' | sed 's|${{ github.workspace }}/||g'); do
            git add $dir/banner.webp
            git add $dir/logo.webp
          done
          git commit -m "docs: sync assets for documentation"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
