name: Publish to pub.dev

on:
  push:
    tags:
      - '*-*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    permissions:
      id-token: write # Required for authentication using OIDC
    steps:
      - name: Set up environment
        run: echo "PACKAGE_NAME=$(echo ${{ github.ref_name }} | grep -o '^[a-z0-9]+')" >> $GITHUB_ENV

      - name: Publish package
        uses: dart-lang/setup-dart/.github/actions/publish-package@v1
        with:
          working-directory: packages/${{ env.PACKAGE_NAME }}
