name: Publish to pub.dev

on:
  push:
    tags:
      - '[a-z]+-[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      steps:
      - name: Set up environment
        run: echo "PACKAGE_NAME=$(echo ${{ github.ref_name }} | grep -o '^[a-z]\+')" >> $GITHUB_ENV

      - name: Publish package
        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
        with:
          working-directory: packages/${{ env.PACKAGE_NAME }}
