name: Publish to pub.dev

on:
  push:
    tags:
      - '*-*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    permissions:
      id-token: write # Required for authentication using OIDC
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - name: Set up environment
        run: echo "PACKAGE_NAME=$(echo ${{ github.ref_name }} | grep -o '^[a-z0-9]*')" >> $GITHUB_ENV

      - name: Publish
        run: |
          cd packages/${{ env.PACKAGE_NAME }}
          dart pub publish --force
